// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from './Accordion';
import CallToAction from './CallToAction';
import CardDonationTypes from './CardDonationTypes';
import Carousel from './Carousel';
import DiagramWithIcon from './DiagramWithIcon';
import Files from './Files';
import GridText from './GridText';
import GridTextWithButton from './GridTextWithButton';
import ImagesCircleList from './ImagesCircleList';
import ImagesList from './ImagesList';
import Missions from './Missions';
import NewsList from './NewsList';
import Ods from './Ods';
import OngNumbers from './OngNumbers';
import OngNumbersImage from './OngNumbersImage';
import TextBlock from './TextBlock';
import TextBlockPersonalized from './TextBlockPersonalized';
import Timeline from './Timeline';

export {
	Accordion,
	CallToAction,
	CardDonationTypes,
	Carousel,
	DiagramWithIcon,
	Files,
	GridText,
	GridTextWithButton,
	ImagesCircleList,
	ImagesList,
	Missions,
	NewsList,
	Ods,
	OngNumbers,
	OngNumbersImage,
	TextBlock,
	TextBlockPersonalized,
	Timeline,
};

export const components = {
	accordion: Accordion,
	call_to_action: CallToAction,
	card_donation_types: CardDonationTypes,
	carousel: Carousel,
	diagram_with_icon: DiagramWithIcon,
	files: Files,
	grid_text: GridText,
	grid_text_with_button: GridTextWithButton,
	images_circle_list: ImagesCircleList,
	images_list: ImagesList,
	missions: Missions,
	news_list: NewsList,
	ods: Ods,
	ong_numbers: OngNumbers,
	ong_numbers_image: OngNumbersImage,
	text_image_block: TextBlock,
	text_block_personalized: TextBlockPersonalized,
	timeline: Timeline,
};
