// This file is generated by Slice Machine. Update with care!

import Accordion from './Accordion';
import CallToAction from './CallToAction';
import CardDonationTypes from './CardDonationTypes';
import GridText from './GridText';
import ImagesList from './ImagesList';
import Missions from './Missions';
import NewsList from './NewsList';
import Ods from './Ods';
import OngNumbers from './OngNumbers';

export {
	Accordion,
	CallToAction,
	CardDonationTypes,
	GridText,
	ImagesList,
	Missions,
	NewsList,
	Ods,
	OngNumbers,
};

export const components = {
	accordion: Accordion,
	call_to_action: CallToAction,
	card_donation_types: CardDonationTypes,
	grid_text: GridText,
	images_list: ImagesList,
	missions: Missions,
	news_list: NewsList,
	ods: Ods,
	ong_numbers: OngNumbers,
};
