// This file is generated by Slice Machine. Update with care!

import Accordion from './Accordion';
import CallToAction from './CallToAction';
import CardDonationTypes from './CardDonationTypes';
import Files from './Files';
import GridText from './GridText';
import GridTextWithButton from './GridTextWithButton';
import ImagesList from './ImagesList';
import Missions from './Missions';
import NewsList from './NewsList';
import Ods from './Ods';
import OngNumbers from './OngNumbers';
import OngNumbersImage from './OngNumbersImage';
import TestimonialCarousel from './TestimonialCarousel';
import TextBlock from './TextBlock';

export {
	Accordion,
	CallToAction,
	CardDonationTypes,
	Files,
	GridText,
	GridTextWithButton,
	ImagesList,
	Missions,
	NewsList,
	Ods,
	OngNumbers,
	OngNumbersImage,
 	TestimonialCarousel,
	TextBlock,
};

export const components = {
	accordion: Accordion,
	call_to_action: CallToAction,
	card_donation_types: CardDonationTypes,
	files: Files,
	grid_text: GridText,
	grid_text_with_button: GridTextWithButton,
	images_list: ImagesList,
	missions: Missions,
	news_list: NewsList,
	ods: Ods,
	ong_numbers: OngNumbers,
	ong_numbers_image: OngNumbersImage,
	testimonial_carousel: TestimonialCarousel,
	text_image_block: TextBlock,
};
